run:
  go: "1.18"
  deadline: 5m
  build-tags:
    - integration
linters:
  enable:
    - bodyclose
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - revive
    - gosec
    - lll
    - misspell
    - nestif
    - testpackage
    - unparam
    - whitespace
    - wsl
issues:
  include:
    - EXC0002
