run:
  deadline: 5m
  build-tags:
    - integration
linters:
  enable:
    - bodyclose
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gosec
    - lll
    - misspell
    - nestif
    - testpackage
    - unparam
    - whitespace
    - wsl
linters-settings:
  gosec:
    excludes:
      - G204
issues:
  include:
    - EXC0002
