name: Tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Lint allowed branch names
        uses: lekterable/branchlint-action@1.2.0
        with:
          allowed: |
            /^(.+:)?bugfix/.+/i
            /^(.+:)?docs?/.+/i
            /^(.+:)?feature/.+/i
            /^(.+:)?hotfix/.+/i
            /^(.+:)?major/.+/i
            /^(.+:)?misc/.+/i
            /^(.+:)?develop$/i
      - 
        # Run only for release branch
        if: ${{ github.base_ref == 'release' }}
        name: Check for changelog pattern
        uses: JJ/github-pr-contains-action@v1
        with:
          github-token: ${{ github.token }}
          bodyContains: 'Changelog:'
