name: "Tests"

on:
  push:
    branches-ignore:
      - "develop"
      - "master"

env:
  GO_VERSION: "1.16"

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: "Pull dependencies"
        run: go mod vendor
      -
        name: "Unit tests"
        run: make test
      -
        name: "Linter"
        run: make lint
      -
        name: "Send coverage"
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: "Pull dependencies"
        run: go mod vendor
      -
        name: "Integration tests"
        run: make test-integration


  tests-windows:
    name: Unit tests windows
    runs-on: windows-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: "Pull dependencies"
        run: go mod vendor
      -
        name: "Unit tests"
        run: make test
      -
        name: "Linter"
        run: make lint

  integration-tests-windows:
    name: Integration tests windows
    runs-on: windows-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: "Pull dependencies"
        run: go mod vendor
      -
        name: "Integration tests"
        run: make test-integration
