on:
  release:
    types: [published]

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run goreleaser-xcgo in docker container
        run: >-
          docker run --privileged --rm
          -e GO_VERSION=1.16
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          -v $PWD:/go/src/github.com/wakatime/wakatime-cli
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /go/src/github.com/wakatime/wakatime-cli
          mailchain/goreleaser-xcgo --rm-dist
